
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Trash2, Save, Video, Play, Edit } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
    DialogFooter,
} from "@/components/ui/dialog";
import { useDemoVideos, useCreateDemoVideo, useUpdateDemoVideo, useDeleteDemoVideo } from "@/hooks/useContent";
import { DemoVideo } from "@/types/content";
import { DeleteConfirmDialog } from "../DeleteConfirmDialog";

export default function DemoManager() {
    const { data: videos = [] } = useDemoVideos();
    const createDemoVideoMutation = useCreateDemoVideo();
    const updateDemoVideoMutation = useUpdateDemoVideo();
    const deleteDemoVideoMutation = useDeleteDemoVideo();

    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [editingVideo, setEditingVideo] = useState<DemoVideo | null>(null);
    const { toast } = useToast();

    // Delete state
    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
    const [videoToDelete, setVideoToDelete] = useState<string | null>(null);
    const [isDeleting, setIsDeleting] = useState(false);

    // Form State
    const [formData, setFormData] = useState<Partial<DemoVideo>>({
        title: "",
        description: "",
        youtubeUrl: "",
        thumbnail: "🎬",
        duration: "",
    });

    // Removed manual loadVideos

    const handleOpenDialog = (video?: DemoVideo) => {
        if (video) {
            setEditingVideo(video);
            setFormData(video);
        } else {
            setEditingVideo(null);
            setFormData({
                title: "",
                description: "",
                youtubeUrl: "",
                thumbnail: "🎬",
                duration: "",
            });
        }
        setIsDialogOpen(true);
    };

    const handleSave = async () => {
        if (!formData.title || !formData.youtubeUrl) {
            toast({
                title: "Error",
                description: "Title and YouTube URL are required",
                variant: "destructive",
            });
            return;
        }

        try {
            if (editingVideo) {
                await updateDemoVideoMutation.mutateAsync({ ...editingVideo, ...formData });
                toast({ title: "Updated", description: "Demo video updated successfully" });
            } else {
                await createDemoVideoMutation.mutateAsync({
                    // id: generated by server
                    title: formData.title || "",
                    description: formData.description || "",
                    youtubeUrl: formData.youtubeUrl || "",
                    thumbnail: formData.thumbnail || "🎬",
                    duration: formData.duration || "",
                });
                toast({ title: "Created", description: "New demo video added" });
            }
            setIsDialogOpen(false);
        } catch (error) {
            toast({ title: "Error", description: "Operation failed", variant: "destructive" });
        }
    };

    const handleDelete = (id: string) => {
        setVideoToDelete(id);
        setDeleteDialogOpen(true);
    };

    const confirmDelete = async () => {
        if (!videoToDelete) return;
        setIsDeleting(true);
        try {
            await deleteDemoVideoMutation.mutateAsync(videoToDelete);
            toast({ title: "Deleted", description: "Video removed successfully" });
        } catch (error) {
            toast({ title: "Error", description: "Failed to delete", variant: "destructive" });
        } finally {
            setIsDeleting(false);
            setDeleteDialogOpen(false);
            setVideoToDelete(null);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center bg-card p-6 rounded-xl border shadow-sm">
                <div>
                    <h2 className="text-2xl font-bold flex items-center gap-2">
                        <Video className="w-6 h-6 text-primary" />
                        ডেমো ভিডিও ম্যানেজার
                    </h2>
                    <p className="text-muted-foreground">ওয়েবসাইটের ডেমো পেজের ভিডিওগুলো ম্যানেজ করুন</p>
                </div>
                <Button onClick={() => handleOpenDialog()} className="gap-2">
                    <Plus className="w-4 h-4" /> নতুন ভিডিও
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {videos.map((video) => (
                    <div key={video.id} className="bg-card border rounded-xl overflow-hidden group hover:shadow-md transition-all">
                        <div className="aspect-video bg-muted relative flex items-center justify-center">
                            {video.youtubeUrl ? (
                                <img
                                    src={`https://img.youtube.com/vi/${getYouTubeID(video.youtubeUrl)}/hqdefault.jpg`}
                                    alt={video.title}
                                    className="w-full h-full object-cover opacity-80"
                                    onError={(e) => (e.currentTarget.src = "https://placehold.co/600x400?text=No+Thumbnail")}
                                />
                            ) : (
                                <span className="text-4xl">{video.thumbnail}</span>
                            )}
                            <div className="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity">
                                <Play className="w-12 h-12 text-white fill-white/50" />
                            </div>
                        </div>

                        <div className="p-4">
                            <div className="flex justify-between items-start mb-2">
                                <h3 className="font-bold line-clamp-1">{video.title}</h3>
                                <span className="text-xs bg-muted px-2 py-1 rounded">{video.duration}</span>
                            </div>
                            <p className="text-sm text-muted-foreground line-clamp-2 mb-4 h-10">
                                {video.description}
                            </p>

                            <div className="flex gap-2">
                                <Button variant="outline" size="sm" className="flex-1 gap-1" onClick={() => handleOpenDialog(video)}>
                                    <Edit className="w-3 h-3" /> Edit
                                </Button>
                                <Button variant="destructive" size="sm" className="w-10 px-0" onClick={() => handleDelete(video.id)}>
                                    <Trash2 className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Edit/Create Dialog */}
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogContent className="sm:max-w-[500px]">
                    <DialogHeader>
                        <DialogTitle>{editingVideo ? "ভিডিও এডিট করুন" : "নতুন ভিডিও যোগ করুন"}</DialogTitle>
                        <div className="sr-only">
                            {/* Accessibility Description */}
                            <p>Fill in the details for the demo video.</p>
                        </div>
                    </DialogHeader>

                    <div className="space-y-4 py-4">
                        <div className="space-y-2">
                            <label className="text-sm font-medium">ভিডিও টাইটেল</label>
                            <Input
                                value={formData.title}
                                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                                placeholder="Ex: AI দিয়ে ল্যান্ডিং পেজ তৈরি"
                            />
                        </div>

                        <div className="space-y-2">
                            <label className="text-sm font-medium">YouTube লিংক</label>
                            <div className="flex items-center gap-2">
                                <Video className="w-4 h-4 text-muted-foreground" />
                                <Input
                                    value={formData.youtubeUrl}
                                    onChange={(e) => setFormData({ ...formData, youtubeUrl: e.target.value })}
                                    placeholder="https://www.youtube.com/watch?v=..."
                                />
                            </div>
                            {formData.youtubeUrl && (
                                <p className="text-xs text-muted-foreground">
                                    Preview: <a href={formData.youtubeUrl} target="_blank" className="text-primary hover:underline">Link Check</a>
                                </p>
                            )}
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <label className="text-sm font-medium">ভিডিও দৈর্ঘ্য (Duration)</label>
                                <Input
                                    value={formData.duration}
                                    onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                                    placeholder="Ex: ১০:৩২"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium">আইকন (Emoji/Text)</label>
                                <Input
                                    value={formData.thumbnail}
                                    onChange={(e) => setFormData({ ...formData, thumbnail: e.target.value })}
                                    placeholder="Ex: 🎬"
                                />
                            </div>
                        </div>

                        <div className="space-y-2">
                            <label className="text-sm font-medium">বিবরণ</label>
                            <Textarea
                                value={formData.description}
                                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                                placeholder="ভিডিও সম্পর্কে ছোট একটি বিবরণ..."
                            />
                        </div>
                    </div>

                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsDialogOpen(false)}>বাতিল</Button>
                        <Button onClick={handleSave} className="gap-2">
                            <Save className="w-4 h-4" /> সংরক্ষণ করুন
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>


            <DeleteConfirmDialog
                open={deleteDialogOpen}
                onOpenChange={setDeleteDialogOpen}
                onConfirm={confirmDelete}
                title="Delete Video?"
                description="Are you sure you want to delete this demo video?"
                isLoading={isDeleting}
            />
        </div >
    );
}

// Helper to extract ID
function getYouTubeID(url: string) {
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
    const match = url.match(regExp);
    return (match && match[2].length === 11) ? match[2] : null;
}
