const mongoose = require('mongoose');

const OrderSchema = new mongoose.Schema({
    // Tracking
    orderId: { type: String, required: true, unique: true }, // Custom ID e.g. ZC-1024

    // Customer Info
    customerName: { type: String, required: true },
    whatsapp: { type: String, required: true },
    email: { type: String },
    address: { type: String }, // Simplified from location object cause frontend sents string

    // Order Details
    orderType: { type: String, enum: ['Template', 'Custom Request'], required: true },

    // Items (For Cart)
    items: [{
        projectId: { type: String },
        title: { type: String },
        price: { type: Number }
    }],

    // Legacy/Single Support (Optional)
    projectRef: { type: String }, // Changed to String to support slugs
    projectName: { type: String },

    // If Custom Request
    customRequirements: {
        websiteType: { type: String },
        category: { type: String },
        pages: [{ type: String }],
        features: [{ type: String }],
        referenceLinks: [{ type: String }],
        budgetRange: { type: String },
        deadline: { type: String },
        notes: { type: String }
    },

    // Files (Up to 5)
    files: [{
        name: { type: String },
        url: { type: String } // Coudinary URL
    }],

    // Financials
    totalPrice: { type: Number },
    paymentReference: { type: String }, // Generated by frontend
    paymentStatus: { type: String, enum: ['Pending', 'Paid', 'Refunded'], default: 'Pending' },

    // Status
    status: { type: String, enum: ['Pending', 'Processing', 'In Progress', 'Under Review', 'Delivered', 'Cancelled'], default: 'Pending' },

    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Order', OrderSchema);
